name: Petfinder API Test Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all tests
        run: pytest tests/
        env:
          PETFINDER_CLIENT_ID: ${{ secrets.PETFINDER_CLIENT_ID }}
          PETFINDER_CLIENT_SECRET: ${{ secrets.PETFINDER_CLIENT_SECRET }}

      - name: Run animal types test
        run: pytest tests/test_animal_types.py

      - name: Run dog breeds test
        run: pytest tests/test_dog_breeds.py

      - name: Run Golden Retriever search test
        run: pytest tests/test_golden_retriever_search.py

      - name: Run mock test (offline)
        run: pytest tests/test_mocked_animal_types.py

      # Optional: performance test (if enabled with Locust)
      # You may need to skip this in CI or run in a separate job.
      # - name: Install Locust and test
      #   run: locust -f performance/locustfile.py --headless -u 1 -r 1 --run-time 10s --host=https://api.petfinder.com
