name: Petfinder API Test Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create reports directory
        run: mkdir -p reports

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html
          pip install -e .  # Install the package in development mode

      - name: Run unit tests
        run: pytest tests/ -v -m "unit" --html=reports/unit-tests-report.html --self-contained-html

      - name: Run integration tests
        run: pytest tests/ -v -m "integration" --html=reports/integration-tests-report.html --self-contained-html
        env:
          PETFINDER_CLIENT_ID: ${{ secrets.PETFINDER_CLIENT_ID }}
          PETFINDER_CLIENT_SECRET: ${{ secrets.PETFINDER_CLIENT_SECRET }}

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            reports/unit-tests-report.html
            reports/integration-tests-report.html